# Dentro del bloque location /api/
location ~ \.php$ {
    # CAMBIADO PARA DOCKER: Apunta al servicio de docker-compose
    fastcgi_pass php-fpm:9000;
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $request_filename;
}