<?php
namespace App\Models\Services;

/**
 * Cadenas traducidas para correos electrónicos (ES, EN, PT).
 * Uso: MailLang::get('es' | 'en' | 'pt')
 */
class MailLang {
    private static $strings = [
        'es' => [
            'footer_developed' => 'Desarrollado por Gekos.uy & UDELAR - Unidad de Reactivos y Biomodelos de Experimentación',
            'subtitle_bioterios' => 'Desarrollado para Bioterios',

            'reg_subject' => 'Confirma tu cuenta',
            'reg_title' => '¡Bienvenido a GROBO!',
            'reg_hello' => 'Hola',
            'reg_created' => 'Se ha creado una cuenta para ti en la institución',
            'reg_user' => 'Has sido registrado como usuario:',
            'reg_confirm_paragraph' => 'Es necesario que confirmes tu correo electrónico para activar tu acceso. Haz clic en el botón inferior para continuar.',
            'reg_btn' => 'CONFIRMAR MI CUENTA',

            'reset_subject' => 'Recuperar contraseña',
            'reset_title' => 'Restablecer contraseña',
            'reset_hello' => 'Hola',
            'reset_paragraph' => 'Has solicitado restablecer tu clave para la institución',
            'reset_paragraph2' => 'Haz clic en el botón inferior para definir una nueva contraseña. El enlace es válido por tiempo limitado.',
            'reset_btn' => 'CAMBIAR CONTRASEÑA',

            'insumo_subject' => 'Actualización Pedido de Insumos',
            'insumo_title' => 'Actualización de Pedido',
            'insumo_hello' => 'Hola',
            'insumo_updated' => 'Tu pedido de insumos',
            'insumo_has_been' => 'ha sido actualizado a estado:',
            'insumo_detail' => 'Detalle de productos solicitados:',
            'insumo_observations' => 'Observaciones del Administrador:',
            'insumo_btn' => 'VER MI PEDIDO',

            'animal_subject' => 'Solicitud Animales',
            'animal_title' => 'Confirmación de Solicitud',
            'animal_hello' => 'Hola',
            'animal_received' => 'Hemos recibido correctamente tu solicitud de animales vivos. Aquí tienes el resumen:',
            'animal_order' => 'Pedido',
            'animal_protocol' => 'Protocolo:',
            'animal_species' => 'Especie:',
            'animal_cepa' => 'Cepa/Sub:',
            'animal_details' => 'Detalles:',
            'animal_males' => 'MACHOS',
            'animal_females' => 'HEMBRAS',
            'animal_indist' => 'INDIST.',
            'animal_total' => 'TOTAL',
            'animal_fecha_retiro' => 'Fecha Retiro:',
            'animal_aclaraciones' => 'Aclaraciones:',
            'animal_sin_obs' => 'Sin observaciones.',

            'reactivo_subject' => 'Solicitud de reactivos',
            'reactivo_title' => 'Confirmación de Solicitud',
            'reactivo_hello' => 'Hola',
            'reactivo_received' => 'Hemos recibido correctamente tu solicitud de reactivos/insumos.',
            'reactivo_insumo' => 'Insumo:',
            'reactivo_cantidad' => 'Cantidad:',
            'reactivo_fecha_retiro' => 'Fecha Retiro:',

            'insumo_exp_subject' => 'Solicitud Insumos',
            'insumo_exp_title' => 'Solicitud de Insumos',
            'insumo_exp_hello' => 'Hola',
            'insumo_exp_registered' => 'Se ha registrado tu solicitud para el departamento',
            'insumo_exp_sin_depto' => 'Sin Departamento',
            'insumo_exp_pedido' => 'N° Pedido:',
            'insumo_exp_fecha' => 'Fecha:',
            'insumo_exp_retiro' => 'Retiro estimado:',
            'insumo_exp_a_coordinar' => 'A coordinar',
            'insumo_exp_nota' => 'Nota:',
            'insumo_exp_descripcion' => 'Descripción',
            'insumo_exp_cant' => 'Cant.',
            'insumo_exp_unidad' => 'Unidad',
            'insumo_exp_btn' => 'IR AL SISTEMA',

            'protocol_subject' => 'Resolución de Protocolo:',
            'protocol_approved' => 'APROBADO',
            'protocol_rejected' => 'RECHAZADO / OBSERVADO',
            'protocol_title' => 'Resolución de Solicitud',
            'protocol_hello' => 'Hola',
            'protocol_processed' => 'ha procesado tu solicitud para el protocolo:',
            'protocol_status' => 'Estado de la Solicitud',
            'protocol_comments' => 'Comentarios / Motivo:',
            'protocol_sin_comentarios' => 'Sin comentarios adicionales.',
            'protocol_btn' => 'VER MIS PROTOCOLOS',

            'form_finalized_subject' => 'NUEVA ALTA:',
            'form_finalized_title' => 'Formulario Finalizado',
            'form_finalized_btn' => 'VER FORMULARIOS',

            'delete_code_subject' => 'Código de verificación - Eliminación total de usuario',
            'delete_code_title' => 'Código de verificación',
            'delete_code_hello' => 'Hola',
            'delete_code_intro' => 'Has solicitado la eliminación total del usuario',
            'delete_code_code' => 'Tu código de verificación es:',
            'delete_code_expires' => 'Válido por 10 minutos.',
            'delete_summary_subject' => 'Resumen de eliminación total de usuario',
            'delete_summary_title' => 'Eliminación completada',
            'delete_summary_intro' => 'Se ha eliminado el usuario y todos sus datos asociados.',
            'delete_summary_user' => 'Usuario eliminado:',
            'delete_summary_code' => 'Código utilizado:',
            'delete_summary_detail' => 'Detalle eliminado:',

            'msg_int_title' => 'Mensaje en GROBO',
            'msg_int_hello' => 'Hola',
            'msg_int_intro' => 'Recibió el siguiente mensaje en GROBO. También puede verlo en la sección Mensajes del sistema.',
            'msg_int_from' => 'Remitente:',
            'msg_int_subject_label' => 'Asunto:',
        ],
        'en' => [
            'footer_developed' => 'Developed by Gekos.uy & UDELAR - Unit of Reagents and Experimentation Biomodels',
            'subtitle_bioterios' => 'Developed for Animal Facilities',

            'reg_subject' => 'Confirm your account',
            'reg_title' => 'Welcome to GROBO!',
            'reg_hello' => 'Hello',
            'reg_created' => 'An account has been created for you at the institution',
            'reg_user' => 'You have been registered as user:',
            'reg_confirm_paragraph' => 'You need to confirm your email to activate your access. Click the button below to continue.',
            'reg_btn' => 'CONFIRM MY ACCOUNT',

            'reset_subject' => 'Recover password',
            'reset_title' => 'Reset password',
            'reset_hello' => 'Hello',
            'reset_paragraph' => 'You have requested to reset your password for the institution',
            'reset_paragraph2' => 'Click the button below to set a new password. The link is valid for a limited time.',
            'reset_btn' => 'CHANGE PASSWORD',

            'insumo_subject' => 'Supplies Order Update',
            'insumo_title' => 'Order Update',
            'insumo_hello' => 'Hello',
            'insumo_updated' => 'Your supplies order',
            'insumo_has_been' => 'has been updated to status:',
            'insumo_detail' => 'Requested products detail:',
            'insumo_observations' => 'Administrator notes:',
            'insumo_btn' => 'VIEW MY ORDER',

            'animal_subject' => 'Animal Request',
            'animal_title' => 'Request Confirmation',
            'animal_hello' => 'Hello',
            'animal_received' => 'We have received your live animal request. Here is the summary:',
            'animal_order' => 'Order',
            'animal_protocol' => 'Protocol:',
            'animal_species' => 'Species:',
            'animal_cepa' => 'Strain/Sub:',
            'animal_details' => 'Details:',
            'animal_males' => 'MALES',
            'animal_females' => 'FEMALES',
            'animal_indist' => 'UNSPEC.',
            'animal_total' => 'TOTAL',
            'animal_fecha_retiro' => 'Pick-up date:',
            'animal_aclaraciones' => 'Notes:',
            'animal_sin_obs' => 'No notes.',

            'reactivo_subject' => 'Reagents request',
            'reactivo_title' => 'Request Confirmation',
            'reactivo_hello' => 'Hello',
            'reactivo_received' => 'We have received your reagents/supplies request.',
            'reactivo_insumo' => 'Item:',
            'reactivo_cantidad' => 'Quantity:',
            'reactivo_fecha_retiro' => 'Pick-up date:',

            'insumo_exp_subject' => 'Supplies Request',
            'insumo_exp_title' => 'Supplies Request',
            'insumo_exp_hello' => 'Hello',
            'insumo_exp_registered' => 'Your request has been registered for the department',
            'insumo_exp_sin_depto' => 'No Department',
            'insumo_exp_pedido' => 'Order No.:',
            'insumo_exp_fecha' => 'Date:',
            'insumo_exp_retiro' => 'Estimated pick-up:',
            'insumo_exp_a_coordinar' => 'To be arranged',
            'insumo_exp_nota' => 'Note:',
            'insumo_exp_descripcion' => 'Description',
            'insumo_exp_cant' => 'Qty',
            'insumo_exp_unidad' => 'Unit',
            'insumo_exp_btn' => 'GO TO SYSTEM',

            'protocol_subject' => 'Protocol Decision:',
            'protocol_approved' => 'APPROVED',
            'protocol_rejected' => 'REJECTED / OBSERVATIONS',
            'protocol_title' => 'Request Decision',
            'protocol_hello' => 'Hello',
            'protocol_processed' => 'has processed your request for the protocol:',
            'protocol_status' => 'Request Status',
            'protocol_comments' => 'Comments / Reason:',
            'protocol_sin_comentarios' => 'No additional comments.',
            'protocol_btn' => 'VIEW MY PROTOCOLS',

            'form_finalized_subject' => 'NEW SIGN-UP:',
            'form_finalized_title' => 'Form Completed',
            'form_finalized_btn' => 'VIEW FORMS',

            'delete_code_subject' => 'Verification code - Full user deletion',
            'delete_code_title' => 'Verification code',
            'delete_code_hello' => 'Hello',
            'delete_code_intro' => 'You have requested full deletion of user',
            'delete_code_code' => 'Your verification code is:',
            'delete_code_expires' => 'Valid for 10 minutes.',
            'delete_summary_subject' => 'Full user deletion summary',
            'delete_summary_title' => 'Deletion completed',
            'delete_summary_intro' => 'The user and all associated data have been deleted.',
            'delete_summary_user' => 'Deleted user:',
            'delete_summary_code' => 'Code used:',
            'delete_summary_detail' => 'Deleted detail:',

            'msg_int_title' => 'Message in GROBO',
            'msg_int_hello' => 'Hello',
            'msg_int_intro' => 'You received the following message in GROBO. You can also read it in the Messages section of the system.',
            'msg_int_from' => 'From:',
            'msg_int_subject_label' => 'Subject:',
        ],
        'pt' => [
            'footer_developed' => 'Desenvolvido por Gekos.uy & UDELAR - Unidade de Reagentes e Biomodelos de Experimentação',
            'subtitle_bioterios' => 'Desenvolvido para Biotérios',

            'reg_subject' => 'Confirme sua conta',
            'reg_title' => 'Bem-vindo ao GROBO!',
            'reg_hello' => 'Olá',
            'reg_created' => 'Foi criada uma conta para você na instituição',
            'reg_user' => 'Você foi registrado como usuário:',
            'reg_confirm_paragraph' => 'É necessário confirmar seu e-mail para ativar seu acesso. Clique no botão abaixo para continuar.',
            'reg_btn' => 'CONFIRMAR MINHA CONTA',

            'reset_subject' => 'Recuperar senha',
            'reset_title' => 'Redefinir senha',
            'reset_hello' => 'Olá',
            'reset_paragraph' => 'Você solicitou a redefinição de sua senha para a instituição',
            'reset_paragraph2' => 'Clique no botão abaixo para definir uma nova senha. O link é válido por tempo limitado.',
            'reset_btn' => 'ALTERAR SENHA',

            'insumo_subject' => 'Atualização do Pedido de Insumos',
            'insumo_title' => 'Atualização do Pedido',
            'insumo_hello' => 'Olá',
            'insumo_updated' => 'Seu pedido de insumos',
            'insumo_has_been' => 'foi atualizado para o estado:',
            'insumo_detail' => 'Detalhe dos produtos solicitados:',
            'insumo_observations' => 'Observações do Administrador:',
            'insumo_btn' => 'VER MEU PEDIDO',

            'animal_subject' => 'Solicitação de Animais',
            'animal_title' => 'Confirmação de Solicitação',
            'animal_hello' => 'Olá',
            'animal_received' => 'Recebemos corretamente sua solicitação de animais vivos. Aqui está o resumo:',
            'animal_order' => 'Pedido',
            'animal_protocol' => 'Protocolo:',
            'animal_species' => 'Espécie:',
            'animal_cepa' => 'Cepa/Sub:',
            'animal_details' => 'Detalhes:',
            'animal_males' => 'MACHOS',
            'animal_females' => 'FÊMEAS',
            'animal_indist' => 'INDIST.',
            'animal_total' => 'TOTAL',
            'animal_fecha_retiro' => 'Data de retirada:',
            'animal_aclaraciones' => 'Esclarecimentos:',
            'animal_sin_obs' => 'Sem observações.',

            'reactivo_subject' => 'Solicitação de reagentes',
            'reactivo_title' => 'Confirmação de Solicitação',
            'reactivo_hello' => 'Olá',
            'reactivo_received' => 'Recebemos corretamente sua solicitação de reagentes/insumos.',
            'reactivo_insumo' => 'Insumo:',
            'reactivo_cantidad' => 'Quantidade:',
            'reactivo_fecha_retiro' => 'Data de retirada:',

            'insumo_exp_subject' => 'Solicitação de Insumos',
            'insumo_exp_title' => 'Solicitação de Insumos',
            'insumo_exp_hello' => 'Olá',
            'insumo_exp_registered' => 'Sua solicitação foi registrada para o departamento',
            'insumo_exp_sin_depto' => 'Sem Departamento',
            'insumo_exp_pedido' => 'N° Pedido:',
            'insumo_exp_fecha' => 'Data:',
            'insumo_exp_retiro' => 'Retirada estimada:',
            'insumo_exp_a_coordinar' => 'A combinar',
            'insumo_exp_nota' => 'Nota:',
            'insumo_exp_descripcion' => 'Descrição',
            'insumo_exp_cant' => 'Qtd',
            'insumo_exp_unidad' => 'Unidade',
            'insumo_exp_btn' => 'IR AO SISTEMA',

            'protocol_subject' => 'Decisão do Protocolo:',
            'protocol_approved' => 'APROVADO',
            'protocol_rejected' => 'REJEITADO / OBSERVAÇÕES',
            'protocol_title' => 'Decisão da Solicitação',
            'protocol_hello' => 'Olá',
            'protocol_processed' => 'processou sua solicitação para o protocolo:',
            'protocol_status' => 'Estado da Solicitação',
            'protocol_comments' => 'Comentários / Motivo:',
            'protocol_sin_comentarios' => 'Sem comentários adicionais.',
            'protocol_btn' => 'VER MEUS PROTOCOLOS',

            'form_finalized_subject' => 'NOVO CADASTRO:',
            'form_finalized_title' => 'Formulário Finalizado',
            'form_finalized_btn' => 'VER FORMULÁRIOS',

            'delete_code_subject' => 'Código de verificação - Eliminação total de usuário',
            'delete_code_title' => 'Código de verificação',
            'delete_code_hello' => 'Olá',
            'delete_code_intro' => 'Você solicitou a eliminação total do usuário',
            'delete_code_code' => 'Seu código de verificação é:',
            'delete_code_expires' => 'Válido por 10 minutos.',
            'delete_summary_subject' => 'Resumo da eliminação total de usuário',
            'delete_summary_title' => 'Eliminação concluída',
            'delete_summary_intro' => 'O usuário e todos os dados associados foram eliminados.',
            'delete_summary_user' => 'Usuário eliminado:',
            'delete_summary_code' => 'Código utilizado:',
            'delete_summary_detail' => 'Detalhe eliminado:',

            'msg_int_title' => 'Mensagem no GROBO',
            'msg_int_hello' => 'Olá',
            'msg_int_intro' => 'Você recebeu a seguinte mensagem no GROBO. Também pode vê-la na seção Mensagens do sistema.',
            'msg_int_from' => 'Remetente:',
            'msg_int_subject_label' => 'Assunto:',
        ],
    ];

    /**
     * @param string $lang Código de idioma (es, en, pt). Si no existe, se usa 'es'.
     * @return array<string, string>
     */
    public static function get($lang) {
        $lang = strtolower(trim($lang ?: 'es'));
        if (!isset(self::$strings[$lang])) {
            $lang = 'es';
        }
        return self::$strings[$lang];
    }
}
